build(macos): Use C++17
To address:

In file included from src/itkWASMImageIOBase.cxx:18:
In file included from include/itkWASMImageIOBase.h:23:
In file included from Modules/IO/ImageBase/include/itkImageIOBase.h:30:
In file included from Modules/Core/Common/include/itkSymmetricSecondRankTensor.h:29:
In file included from Modules/Core/Common/include/itkSymmetricEigenAnalysis.h:1104:
In file included from Modules/Core/Common/include/itkSymmetricEigenAnalysis.hxx:22:
Modules/Core/Common/include/itkMakeUniqueForOverwrite.h:76:14: error: no member named 'make_unique_for_overwrite' in namespace 'std'

We could revisit after the GitHub Action Hosted Runner is updated from
macos-11 to macos-12. Windows needs 20 to avoid compile errors.