build(Windows): Simplify cbor pair initialization
Addresses:

C:\itk-wasm\src\itkWASMMeshIO.cxx(316): error C7555: use of designated initializers requires at least '/std:c++20'

Without the use of C++20.

Also build cbor cpp-base64 as static libraries to avoid difficulties
locating them.