fix(apply-presentation-state-to-image): Fix output image lifetime
The itk::Image needs to be around with the itk::wasm::OutputImage
destructor is called.

Addresses:

```
Error: failed to run main module `./apply-presentation-state-to-image.wasi.wasm`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0xc9932 - <unknown>!fwrite
           1: 0x1803c3 - <unknown>!itk::WasmImageIO::Write(void const*)
           2: 0x113db7 - itk::ImageFileWriter<itk::Image<unsigned char, (unsigned int)2> >::GenerateData()
                           at /ITK/Modules/IO/ImageBase/include/itkImageFileWriter.hxx:378:14
           3: 0x1159a3 - itk::ImageFileWriter<itk::Image<unsigned char, (unsigned int)2> >::Write()
                           at /ITK/Modules/IO/ImageBase/include/itkImageFileWriter.hxx:314:11
           4: 0x1136e7 - itk::ImageFileWriter<itk::Image<unsigned char, (unsigned int)2> >::Update()
                           at /ITK/Modules/IO/ImageBase/include/itkImageFileWriter.h:178:11
           5: 0x1126e1 - void itk::WriteImage<itk::SmartPointer<itk::Image<unsigned char, (unsigned int)2> const>&>(itk::SmartPointer<itk::Image<unsigned char, (unsigned int)2> const>&, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> > const&, bool)
                           at /ITK/Modules/IO/ImageBase/include/itkImageFileWriter.h:259:11
           6: 0x1098ec - itk::wasm::OutputImage<itk::Image<unsigned char, (unsigned int)2> >::~OutputImage()
                           at /ITKWebAssemblyInterface/include/itkOutputImage.h:104:7
           7: 0xf9e13 - __main_argc_argv
                           at /work/apply-presentation-state-to-image.cxx:715:1
           8: 0xd483f - <unknown>!__main_void
           9: 0x55ce27 - itk_wasm_delayed_start
                           at /ITKWebAssemblyInterface/src/initialization.cxx:51:17
          10: 0x55ce62 - _start
                           at /ITKWebAssemblyInterface/src/initialization.cxx:61:26
    2: wasm trap: uninitialized element
(base)
```