fix(apply-presentation-state-to-json): Avoid crash with empty description
Addresses:

```
╰─λ wasmtime ./apply-presentation-state-to-image.wasi.wasm --dir=../test/data/input -- ../test/data/input/gsps-pstate-test-input-image.dcm ../test/data/input/gsps-pstate-test-input-pstate.dcm test.json test.iwi.cbor
W: SamplesPerPixel (0028,0002) absent in ImagePixelModule (type 1)
W: PhotometricInterpretation (0028,0004) absent in ImagePixelModule (type 1)
W: Rows (0028,0010) absent in ImagePixelModule (type 1)
W: Columns (0028,0011) absent in ImagePixelModule (type 1)
W: BitsAllocated (0028,0100) absent in ImagePixelModule (type 1)
W: BitsStored (0028,0101) absent in ImagePixelModule (type 1)
W: HighBit (0028,0102) absent in ImagePixelModule (type 1)
W: PixelRepresentation (0028,0103) absent in ImagePixelModule (type 1)
W: SamplesPerPixel (0028,0002) absent in ImagePixelModule (type 1)
W: PhotometricInterpretation (0028,0004) absent in ImagePixelModule (type 1)
W: Rows (0028,0010) absent in ImagePixelModule (type 1)
W: Columns (0028,0011) absent in ImagePixelModule (type 1)
W: BitsAllocated (0028,0100) absent in ImagePixelModule (type 1)
W: BitsStored (0028,0101) absent in ImagePixelModule (type 1)
W: HighBit (0028,0102) absent in ImagePixelModule (type 1)
W: PixelRepresentation (0028,0103) absent in ImagePixelModule (type 1)
1633838444ITKWASMTEST2
1953066862
Assertion failed: str != 0 (/ITKWebAssemblyInterface-build/_deps/rapidjson_lib-src/include/rapidjson/document.h: NotNullStrLen: 424)
Error: failed to run main module `./apply-presentation-state-to-image.wasi.wasm`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0xc6c0c - <unknown>!abort
           1: 0xc8420 - <unknown>!__assert_fail
           2: 0x1274e4 - rapidjson::GenericStringRef<char>::NotNullStrLen(char const*)
                           at /ITKWebAssemblyInterface-build/_deps/rapidjson_lib-src/include/rapidjson/document.h:424:9
           3: 0x127347 - rapidjson::GenericStringRef<char>::GenericStringRef(char const*)
                           at /ITKWebAssemblyInterface-build/_deps/rapidjson_lib-src/include/rapidjson/document.h:400:26
           4: 0x10b4cd - rapidjson::GenericStringRef<char> rapidjson::StringRef<char>(char const*)
                           at /ITKWebAssemblyInterface-build/_deps/rapidjson_lib-src/include/rapidjson/document.h:455:12
           5: 0x1061a5 - dumpPresentationState(std::__2::basic_ostream<char, std::__2::char_traits<char> >&, DVPresentationState&)
                           at /work/apply-presentation-state-to-image.cxx:133:11
           6: 0xf95f1 - __main_argc_argv
                           at /work/apply-presentation-state-to-image.cxx:632:26
           7: 0xd483b - <unknown>!__main_void
           8: 0x55cbe0 - itk_wasm_delayed_start
                           at /ITKWebAssemblyInterface/src/initialization.cxx:51:17
           9: 0x55cc1b - _start
                           at /ITKWebAssemblyInterface/src/initialization.cxx:61:26
    2: wasm trap: wasm `unreachable` instruction executed
(base)
```