fix(bindgen): Add missing .nojekyll
To address:

```
Error: ENOENT: no such file or directory, copyfile '/home/matt/src/ITKCleaver/node_modules/.pnpm/itk-wasm@1.0.0-b.69/node_modules/itk-wasm/src/bindgen/typescript-resources/.nojekyll' -> 'typescript/.nojekll'
```