fix(buffer-to-typed-array): accept SharedArrayBuffer
For:

src/pipeline/internal/run-pipeline-emscripten.ts:122:50 - error TS2345: Argument of type 'ArrayBufferLike' is not assignable to parameter of type 'ArrayBuffer'.
  Type 'SharedArrayBuffer' is missing the following properties from type 'ArrayBuffer': resizable, resize, detached, transfer, transferToFixedLength

122   const data = bufferToTypedArray(componentType, dataUint8.buffer)
                                                     ~~~~~~~~~~~~~~~~