build(Windows): Use C++20 standard
To address:

```
D:\a\im\src\itkWASMImageIO.cxx(337): error C7555: use of designated initializers requires at least '/std:c++20'
883
D:\a\im\src\itkWASMImageIO.cxx(338): error C4576: a parenthesized type followed by an initializer list is a non-standard explicit type conversion syntax
884
D:\a\im\src\itkWASMImageIO.cxx(342): error C7555: use of designated initializers requires at least '/std:c++20'
```

even though these are C constructs. Need to change syntax from C to C++.