ci(cypress): Bump to Node 18.16
To address:

```
> ./src/itk-wasm-cli.js -s packages/dicom -b emscripten-build bindgen \
  --package-name @itk-wasm/dicom --package-description \
  "Read files and images related to DICOM file format." \
  --repository 'https://github.com/InsightSoftwareConsortium/itk-wasm'

undefined:406

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at wasmBinaryInterfaceJson (file:///home/runner/work/itk-wasm/itk-wasm/src/bindgen/wasmBinaryInterfaceJson.js:36:26)
    at file:///home/runner/work/itk-wasm/itk-wasm/src/bindgen/python.js:548:31
    at Array.forEach (<anonymous>)
    at pythonBindings (file:///home/runner/work/itk-wasm/itk-wasm/src/bindgen/python.js:547:16)
    at bindgen (file:///home/runner/work/itk-wasm/itk-wasm/src/bindgen/python.js:555:3)
    at Command.bindgen (file:///home/runner/work/itk-wasm/itk-wasm/src/itk-wasm-cli.js:259:7)
    at Command.listener [as _actionHandler] (/home/runner/work/itk-wasm/itk-wasm/node_modules/commander/lib/command.js:482:17)
    at /home/runner/work/itk-wasm/itk-wasm/node_modules/commander/lib/command.js:1265:65
    at Command._chainOrCall (/home/runner/work/itk-wasm/itk-wasm/node_modules/commander/lib/command.js:1159:12)
```