test(image-io): exclude wasi gdcm write tests
Currently failing in non-Debug builds for unknown reasons with the
latest toolchain update:

Error: failed to run main module `/work/wasi-build/gdcm-write-image.wasi.wasm`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0x1ebfeb - <unknown>!<wasm function 2320>
           1: 0x2d80b - <unknown>!<wasm function 340>
           2: 0x222566 - <unknown>!<wasm function 2725>
           3: 0x2dc60 - <unknown>!<wasm function 348>
       note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable may show more debugging information
    2: memory fault at wasm address 0x4013c708 in linear memory of size 0x590000
    3: wasm trap: out of bounds memory access

    Start 6: gdcm-write-image-iwi-cbor-test
6/6 Test #6: gdcm-write-image-iwi-cbor-test ...***Failed    0.04 sec
Error: failed to run main module `/work/wasi-build/gdcm-write-image.wasi.wasm`