build(wrapping): Fix missing wrapped type for itkWasmTransformIO
Only templated variants for double and float are available,
so alias to the double version of transforms for wrapping.

ITK/build-python/Wrapping/castxml_inputs/itkWasmTransformIO.cxx:26:39:
error: no type named 'WasmTransformIO' in namespace 'itk'
   26 |         using itkWasmTransformIO=itk::WasmTransformIO;
      |                                  ~~~~~^