fix(compress-stringify): improve decode argument type
For:

│ src/interface-type-json-node.ts:33:38 - error TS2345: Argument of type 'ArrayBufferLike' is not assignable to parameter of type 'AllowSharedBufferSource | …
│   Type 'SharedArrayBuffer' is not assignable to type 'AllowSharedBufferSource | undefined'.
│     Type 'SharedArrayBuffer' is missing the following properties from type 'ArrayBuffer': resizable, resize, detached, transfer, transferToFixedLength
│ 33   encoded.direction = decoder.decode(direction.output.buffer);