fix(itkPipeline): return CLI::CallForHelp with -h, --help
This is intended for the two flags as opposed to --help-all.

Also work around:

Error: failed to run main module `wasi-build/mean-squares-versor-registration.wasi.wasm`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0: 0x56479 - mean-squares-versor-registration.wasi.wasm!abort
           1: 0x6834d - __cxa_allocate_exception
                           at /ITKWebAssemblyInterface/src/exceptionShim.cxx:28:3
           2: 0x680c8 - std::__2::__throw_out_of_range[abi:ne180100](char const*)
                           at /usr/wasi-sdk-22.0/share/wasi-sysroot/include/wasm32-wasi/c++/v1/stdexcept:249:3
           3: 0x6801a - std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >::__throw_out_of_range[abi:ne180100]() const
                           at /usr/wasi-sdk-22.0/share/wasi-sysroot/include/wasm32-wasi/c++/v1/string:2117:5
           4: 0x764de - mean-squares-versor-registration.wasi.wasm!itk::wasm::Pipeline::exit(CLI::Error const&)
           5: 0x7151d - __main_argc_argv
                           at /work/mean-squares-versor-registration.cxx:159:3
           6: 0x616f9 - mean-squares-versor-registration.wasi.wasm!__main_void
           7: 0x29bec0 - itk_wasm_delayed_start
                           at /ITKWebAssemblyInterface/src/initialization.cxx:81:17
           8: 0x29befb - _start
                           at /ITKWebAssemblyInterface/src/initialization.cxx:92:26