fix(bindgen): Fix empty options detection
Addresses:

```
src/mesh-to-poly-data-node.ts:24:3 - error TS6133: 'options' is declared but its value is never read.

24   options: MeshToPolyDataOptions = {}
     ~~~~~~~
```